
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborator7
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Cale { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DataCreare { get; set; }
        [DataMember]
        public string Eveniment { get; set; }
        [DataMember]
        public string Persoane { get; set; }
        [DataMember]
        public string Loc { get; set; }
        [DataMember]
        public string Peisaj { get; set; }
        [DataMember]
        public string Sters { get; set; }
    }
}