//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterfacePhoto")]
public interface InterfacePhoto
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/PhotoExist", ReplyAction="http://tempuri.org/InterfacePhoto/PhotoExistResponse")]
    int PhotoExist(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/PhotoExist", ReplyAction="http://tempuri.org/InterfacePhoto/PhotoExistResponse")]
    System.Threading.Tasks.Task<int> PhotoExistAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/AddPhoto", ReplyAction="http://tempuri.org/InterfacePhoto/AddPhotoResponse")]
    void AddPhoto(string caleGUI, System.DateTime dataCrearii, string eveniment, string loc, string persoane);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/AddPhoto", ReplyAction="http://tempuri.org/InterfacePhoto/AddPhotoResponse")]
    System.Threading.Tasks.Task AddPhotoAsync(string caleGUI, System.DateTime dataCrearii, string eveniment, string loc, string persoane);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetNume", ReplyAction="http://tempuri.org/InterfacePhoto/GetNumeResponse")]
    string GetNume(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetNume", ReplyAction="http://tempuri.org/InterfacePhoto/GetNumeResponse")]
    System.Threading.Tasks.Task<string> GetNumeAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetEveniment", ReplyAction="http://tempuri.org/InterfacePhoto/GetEvenimentResponse")]
    string GetEveniment(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetEveniment", ReplyAction="http://tempuri.org/InterfacePhoto/GetEvenimentResponse")]
    System.Threading.Tasks.Task<string> GetEvenimentAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetLoc", ReplyAction="http://tempuri.org/InterfacePhoto/GetLocResponse")]
    string GetLoc(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetLoc", ReplyAction="http://tempuri.org/InterfacePhoto/GetLocResponse")]
    System.Threading.Tasks.Task<string> GetLocAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetDataCrearii", ReplyAction="http://tempuri.org/InterfacePhoto/GetDataCreariiResponse")]
    System.DateTime GetDataCrearii(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetDataCrearii", ReplyAction="http://tempuri.org/InterfacePhoto/GetDataCreariiResponse")]
    System.Threading.Tasks.Task<System.DateTime> GetDataCreariiAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetNames", ReplyAction="http://tempuri.org/InterfacePhoto/GetNamesResponse")]
    string[] GetNames();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetNames", ReplyAction="http://tempuri.org/InterfacePhoto/GetNamesResponse")]
    System.Threading.Tasks.Task<string[]> GetNamesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPersoane", ReplyAction="http://tempuri.org/InterfacePhoto/GetPersoaneResponse")]
    string GetPersoane(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPersoane", ReplyAction="http://tempuri.org/InterfacePhoto/GetPersoaneResponse")]
    System.Threading.Tasks.Task<string> GetPersoaneAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetEvenimentList", ReplyAction="http://tempuri.org/InterfacePhoto/GetEvenimentListResponse")]
    string[] GetEvenimentList(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetEvenimentList", ReplyAction="http://tempuri.org/InterfacePhoto/GetEvenimentListResponse")]
    System.Threading.Tasks.Task<string[]> GetEvenimentListAsync(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetLocList", ReplyAction="http://tempuri.org/InterfacePhoto/GetLocListResponse")]
    string[] GetLocList(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetLocList", ReplyAction="http://tempuri.org/InterfacePhoto/GetLocListResponse")]
    System.Threading.Tasks.Task<string[]> GetLocListAsync(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPersoanaList", ReplyAction="http://tempuri.org/InterfacePhoto/GetPersoanaListResponse")]
    string[] GetPersoanaList(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetPersoanaList", ReplyAction="http://tempuri.org/InterfacePhoto/GetPersoanaListResponse")]
    System.Threading.Tasks.Task<string[]> GetPersoanaListAsync(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetDataCreariiList", ReplyAction="http://tempuri.org/InterfacePhoto/GetDataCreariiListResponse")]
    string[] GetDataCreariiList(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/GetDataCreariiList", ReplyAction="http://tempuri.org/InterfacePhoto/GetDataCreariiListResponse")]
    System.Threading.Tasks.Task<string[]> GetDataCreariiListAsync(string cautare);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/DeletePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/DeletePhotoResponse")]
    void DeletePhoto(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/DeletePhoto", ReplyAction="http://tempuri.org/InterfacePhoto/DeletePhotoResponse")]
    System.Threading.Tasks.Task DeletePhotoAsync(string caleGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/SchimbareCale", ReplyAction="http://tempuri.org/InterfacePhoto/SchimbareCaleResponse")]
    void SchimbareCale(string caleGUI, string caleNouaGUI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfacePhoto/SchimbareCale", ReplyAction="http://tempuri.org/InterfacePhoto/SchimbareCaleResponse")]
    System.Threading.Tasks.Task SchimbareCaleAsync(string caleGUI, string caleNouaGUI);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InterfacePhotoChannel : InterfacePhoto, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InterfacePhotoClient : System.ServiceModel.ClientBase<InterfacePhoto>, InterfacePhoto
{
    
    public InterfacePhotoClient()
    {
    }
    
    public InterfacePhotoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InterfacePhotoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfacePhotoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InterfacePhotoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int PhotoExist(string caleGUI)
    {
        return base.Channel.PhotoExist(caleGUI);
    }
    
    public System.Threading.Tasks.Task<int> PhotoExistAsync(string caleGUI)
    {
        return base.Channel.PhotoExistAsync(caleGUI);
    }
    
    public void AddPhoto(string caleGUI, System.DateTime dataCrearii, string eveniment, string loc, string persoane)
    {
        base.Channel.AddPhoto(caleGUI, dataCrearii, eveniment, loc, persoane);
    }
    
    public System.Threading.Tasks.Task AddPhotoAsync(string caleGUI, System.DateTime dataCrearii, string eveniment, string loc, string persoane)
    {
        return base.Channel.AddPhotoAsync(caleGUI, dataCrearii, eveniment, loc, persoane);
    }
    
    public string GetNume(string caleGUI)
    {
        return base.Channel.GetNume(caleGUI);
    }
    
    public System.Threading.Tasks.Task<string> GetNumeAsync(string caleGUI)
    {
        return base.Channel.GetNumeAsync(caleGUI);
    }
    
    public string GetEveniment(string caleGUI)
    {
        return base.Channel.GetEveniment(caleGUI);
    }
    
    public System.Threading.Tasks.Task<string> GetEvenimentAsync(string caleGUI)
    {
        return base.Channel.GetEvenimentAsync(caleGUI);
    }
    
    public string GetLoc(string caleGUI)
    {
        return base.Channel.GetLoc(caleGUI);
    }
    
    public System.Threading.Tasks.Task<string> GetLocAsync(string caleGUI)
    {
        return base.Channel.GetLocAsync(caleGUI);
    }
    
    public System.DateTime GetDataCrearii(string caleGUI)
    {
        return base.Channel.GetDataCrearii(caleGUI);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetDataCreariiAsync(string caleGUI)
    {
        return base.Channel.GetDataCreariiAsync(caleGUI);
    }
    
    public string[] GetNames()
    {
        return base.Channel.GetNames();
    }
    
    public System.Threading.Tasks.Task<string[]> GetNamesAsync()
    {
        return base.Channel.GetNamesAsync();
    }
    
    public string GetPersoane(string caleGUI)
    {
        return base.Channel.GetPersoane(caleGUI);
    }
    
    public System.Threading.Tasks.Task<string> GetPersoaneAsync(string caleGUI)
    {
        return base.Channel.GetPersoaneAsync(caleGUI);
    }
    
    public string[] GetEvenimentList(string cautare)
    {
        return base.Channel.GetEvenimentList(cautare);
    }
    
    public System.Threading.Tasks.Task<string[]> GetEvenimentListAsync(string cautare)
    {
        return base.Channel.GetEvenimentListAsync(cautare);
    }
    
    public string[] GetLocList(string cautare)
    {
        return base.Channel.GetLocList(cautare);
    }
    
    public System.Threading.Tasks.Task<string[]> GetLocListAsync(string cautare)
    {
        return base.Channel.GetLocListAsync(cautare);
    }
    
    public string[] GetPersoanaList(string cautare)
    {
        return base.Channel.GetPersoanaList(cautare);
    }
    
    public System.Threading.Tasks.Task<string[]> GetPersoanaListAsync(string cautare)
    {
        return base.Channel.GetPersoanaListAsync(cautare);
    }
    
    public string[] GetDataCreariiList(string cautare)
    {
        return base.Channel.GetDataCreariiList(cautare);
    }
    
    public System.Threading.Tasks.Task<string[]> GetDataCreariiListAsync(string cautare)
    {
        return base.Channel.GetDataCreariiListAsync(cautare);
    }
    
    public void DeletePhoto(string caleGUI)
    {
        base.Channel.DeletePhoto(caleGUI);
    }
    
    public System.Threading.Tasks.Task DeletePhotoAsync(string caleGUI)
    {
        return base.Channel.DeletePhotoAsync(caleGUI);
    }
    
    public void SchimbareCale(string caleGUI, string caleNouaGUI)
    {
        base.Channel.SchimbareCale(caleGUI, caleNouaGUI);
    }
    
    public System.Threading.Tasks.Task SchimbareCaleAsync(string caleGUI, string caleNouaGUI)
    {
        return base.Channel.SchimbareCaleAsync(caleGUI, caleNouaGUI);
    }
}
